version: '4'

services:

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.25
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sublate
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
      - app3

  app1: &appbase
    container_name: app1
    hostname: app1
    image: python:slim
    environment:
      - PYTHONPATH=/app
    command: 
      - "sh"
      - "-c"
      - |
        pip install -r /app/requirements.txt
        uvicorn app.main:app --host 0.0.0.0 --port 80 --workers 1 --timeout-keep-alive 65
    volumes:
      - ./:/app
    networks:
      - sublate
    expose:
      - "80"
    depends_on:
      - cache
      - postgres
      - queue

  app2:
    <<: *appbase
    container_name: app2
    hostname: app2
    
  worker:
    container_name: worker
    hostname: worker
    image: python:slim
    environment:
      - PYTHONPATH=/app
    command: 
      - "sh"
      - "-c"
      - |
        pip install -r /app/requirements.txt
        celery -A app.worker worker --concurrency 3 --loglevel=debug
    volumes:
      - ./:/app
    networks:
      - sublate
    depends_on:
      - postgres
      - queue

  cache:
    container_name: redis
    hostname: redis
    image: redis:7.2
    networks:
      - sublate
    ports:
      - "6379:6379"
  
  queue:
    container_name: queue
    hostname: queue
    image: rabbitmq:management
    networks:
      - sublate
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: sublate
      POSTGRES_PASSWORD: DaorMaelon
      POSTGRES_DB: api
    networks:
      - sublate
    ports:
      - "5432:5432"

networks:
  sublate:
    driver: bridge